insert into authors (id, first_name, last_name) values (1, 'Reena', 'McGing');
insert into authors (id, first_name, last_name) values (2, 'Chet', 'Kerkham');
insert into authors (id, first_name, last_name) values (3, 'Albert', 'Basketfield');
insert into authors (id, first_name, last_name) values (4, 'Brigitte', 'Baison');
insert into authors (id, first_name, last_name) values (5, 'Halley', 'Cockrill');
insert into authors (id, first_name, last_name) values (6, 'Rand', 'Wheelwright');
insert into authors (id, first_name, last_name) values (7, 'Millie', 'Barts');
insert into authors (id, first_name, last_name) values (8, 'Arliene', 'Ivanets');
insert into authors (id, first_name, last_name) values (9, 'Amelina', 'Ibbs');
insert into authors (id, first_name, last_name) values (10, 'Clarita', 'Mara');
insert into authors (id, first_name, last_name) values (11, 'Emory', 'Hellis');
insert into authors (id, first_name, last_name) values (12, 'Tiebout', 'Raiker');
insert into authors (id, first_name, last_name) values (13, 'Meriel', 'Galsworthy');
insert into authors (id, first_name, last_name) values (14, 'Hayward', 'Goady');
insert into authors (id, first_name, last_name) values (15, 'Ward', 'Magwood');
insert into authors (id, first_name, last_name) values (16, 'Ginnifer', 'Giddy');
insert into authors (id, first_name, last_name) values (17, 'Rafael', 'Dunthorne');
insert into authors (id, first_name, last_name) values (18, 'Lise', 'Sydney');
insert into authors (id, first_name, last_name) values (19, 'Rosabella', 'Snashall');
insert into authors (id, first_name, last_name) values (20, 'Imelda', 'Barhems');
insert into authors (id, first_name, last_name) values (21, 'Tatiana', 'Santino');
insert into authors (id, first_name, last_name) values (22, 'Patrick', 'MacCawley');
insert into authors (id, first_name, last_name) values (23, 'Mirabella', 'Schultze');
insert into authors (id, first_name, last_name) values (24, 'Minta', 'Storms');
insert into authors (id, first_name, last_name) values (25, 'Annabel', 'Keen');
insert into authors (id, first_name, last_name) values (26, 'Elsey', 'Sawford');
insert into authors (id, first_name, last_name) values (27, 'Ahmed', 'Macconachy');
insert into authors (id, first_name, last_name) values (28, 'Glendon', 'Stuck');
insert into authors (id, first_name, last_name) values (29, 'Juliana', 'Petrowsky');
insert into authors (id, first_name, last_name) values (30, 'Sal', 'M''cowis');
insert into authors (id, first_name, last_name) values (31, 'Reba', 'Gritsaev');
insert into authors (id, first_name, last_name) values (32, 'Romy', 'Brotheridge');
insert into authors (id, first_name, last_name) values (33, 'Hillary', 'Prydden');
insert into authors (id, first_name, last_name) values (34, 'Llywellyn', 'Downing');
insert into authors (id, first_name, last_name) values (35, 'Brocky', 'Bahike');
insert into authors (id, first_name, last_name) values (36, 'Kit', 'Stealey');
insert into authors (id, first_name, last_name) values (37, 'Lin', 'Yuill');
insert into authors (id, first_name, last_name) values (38, 'Hetty', 'Huntington');
insert into authors (id, first_name, last_name) values (39, 'Diane', 'Ovid');
insert into authors (id, first_name, last_name) values (40, 'Ollie', 'Joerning');
insert into authors (id, first_name, last_name) values (41, 'Alexis', 'Feben');
insert into authors (id, first_name, last_name) values (42, 'Hildy', 'Shelley');
insert into authors (id, first_name, last_name) values (43, 'Farra', 'Gellert');
insert into authors (id, first_name, last_name) values (44, 'Chrotoem', 'Dowderswell');
insert into authors (id, first_name, last_name) values (45, 'Dyane', 'Birdsall');
insert into authors (id, first_name, last_name) values (46, 'Ichabod', 'Beniesh');
insert into authors (id, first_name, last_name) values (47, 'Bryanty', 'Neilan');
insert into authors (id, first_name, last_name) values (48, 'Helen', 'Normanell');
insert into authors (id, first_name, last_name) values (49, 'Jillana', 'Sego');
insert into authors (id, first_name, last_name) values (50, 'Lura', 'Danzig');
insert into authors (id, first_name, last_name) values (51, 'Bernetta', 'Vowden');
insert into authors (id, first_name, last_name) values (52, 'Nikkie', 'Duligal');
insert into authors (id, first_name, last_name) values (53, 'Gabriel', 'Maunder');
insert into authors (id, first_name, last_name) values (54, 'El', 'Scoates');
insert into authors (id, first_name, last_name) values (55, 'Brenn', 'Drewery');
insert into authors (id, first_name, last_name) values (56, 'Sisile', 'Mollett');
insert into authors (id, first_name, last_name) values (57, 'Buck', 'McDaid');
insert into authors (id, first_name, last_name) values (58, 'Stevy', 'Maulin');
insert into authors (id, first_name, last_name) values (59, 'Boothe', 'Seiler');
insert into authors (id, first_name, last_name) values (60, 'Amber', 'Rhodes');
insert into authors (id, first_name, last_name) values (61, 'Daffie', 'Gorioli');
insert into authors (id, first_name, last_name) values (62, 'Sonny', 'Carabet');
insert into authors (id, first_name, last_name) values (63, 'Lexine', 'Shire');
insert into authors (id, first_name, last_name) values (64, 'Dallon', 'Fewkes');
insert into authors (id, first_name, last_name) values (65, 'Barbee', 'Scotchmor');
insert into authors (id, first_name, last_name) values (66, 'Averill', 'Delacourt');
insert into authors (id, first_name, last_name) values (67, 'Selma', 'Jinkin');
insert into authors (id, first_name, last_name) values (68, 'Siobhan', 'Twort');
insert into authors (id, first_name, last_name) values (69, 'Bar', 'Seer');
insert into authors (id, first_name, last_name) values (70, 'Don', 'Bachanski');
insert into authors (id, first_name, last_name) values (71, 'Ennis', 'Vint');
insert into authors (id, first_name, last_name) values (72, 'Templeton', 'Swatland');
insert into authors (id, first_name, last_name) values (73, 'Clim', 'Garatty');
insert into authors (id, first_name, last_name) values (74, 'Urbano', 'Presdie');
insert into authors (id, first_name, last_name) values (75, 'Laney', 'Fierman');
insert into authors (id, first_name, last_name) values (76, 'Almeria', 'Lukes');
insert into authors (id, first_name, last_name) values (77, 'Kassandra', 'Kimmons');
insert into authors (id, first_name, last_name) values (78, 'Eleni', 'Phillips');
insert into authors (id, first_name, last_name) values (79, 'Lona', 'Maffy');
insert into authors (id, first_name, last_name) values (80, 'Eleonore', 'Garlick');
insert into authors (id, first_name, last_name) values (81, 'Margie', 'Palmby');
insert into authors (id, first_name, last_name) values (82, 'Amery', 'Darree');
insert into authors (id, first_name, last_name) values (83, 'Lewes', 'Tarling');
insert into authors (id, first_name, last_name) values (84, 'Melisa', 'Arber');
insert into authors (id, first_name, last_name) values (85, 'Shaine', 'Scatchard');
insert into authors (id, first_name, last_name) values (86, 'Othilie', 'Antonacci');
insert into authors (id, first_name, last_name) values (87, 'Elliott', 'Cannop');
insert into authors (id, first_name, last_name) values (88, 'Wilmette', 'Tringham');
insert into authors (id, first_name, last_name) values (89, 'Ade', 'Smy');
insert into authors (id, first_name, last_name) values (90, 'Evelyn', 'Woodford');
insert into authors (id, first_name, last_name) values (91, 'Perle', 'Blagbrough');
insert into authors (id, first_name, last_name) values (92, 'Vincents', 'Skentelbury');
insert into authors (id, first_name, last_name) values (93, 'Beryle', 'Hinnerk');
insert into authors (id, first_name, last_name) values (94, 'Fifine', 'Birtle');
insert into authors (id, first_name, last_name) values (95, 'Vidovik', 'McKennan');
insert into authors (id, first_name, last_name) values (96, 'Vilma', 'Strettell');
insert into authors (id, first_name, last_name) values (97, 'Jennee', 'Pavkovic');
insert into authors (id, first_name, last_name) values (98, 'Grenville', 'Tillot');
insert into authors (id, first_name, last_name) values (99, 'Moria', 'Garford');
insert into authors (id, first_name, last_name) values (100, 'Basile', 'Caro');
insert into authors (id, first_name, last_name) values (101, 'Fielding', 'Fardell');
insert into authors (id, first_name, last_name) values (102, 'Channa', 'Eunson');
insert into authors (id, first_name, last_name) values (103, 'Rhys', 'Goodoune');
insert into authors (id, first_name, last_name) values (104, 'Zonnya', 'Coltherd');
insert into authors (id, first_name, last_name) values (105, 'Berthe', 'Poolman');
insert into authors (id, first_name, last_name) values (106, 'Adolph', 'Cartmel');
insert into authors (id, first_name, last_name) values (107, 'Cheston', 'Gloster');
insert into authors (id, first_name, last_name) values (108, 'Rickie', 'Gyngyll');
insert into authors (id, first_name, last_name) values (109, 'Hermione', 'Fanner');
insert into authors (id, first_name, last_name) values (110, 'Delora', 'Illem');
insert into authors (id, first_name, last_name) values (111, 'Mariellen', 'Jiggle');
insert into authors (id, first_name, last_name) values (112, 'Marlyn', 'Cardnell');
insert into authors (id, first_name, last_name) values (113, 'Berenice', 'Joskowicz');
insert into authors (id, first_name, last_name) values (114, 'Madlen', 'Rumney');
insert into authors (id, first_name, last_name) values (115, 'Alla', 'Phelp');
insert into authors (id, first_name, last_name) values (116, 'Paulina', 'Winspeare');
insert into authors (id, first_name, last_name) values (117, 'Robinetta', 'Parlet');
insert into authors (id, first_name, last_name) values (118, 'Bearnard', 'De Ath');
insert into authors (id, first_name, last_name) values (119, 'Ludovico', 'Lademann');
insert into authors (id, first_name, last_name) values (120, 'Ellissa', 'Pigrome');
insert into authors (id, first_name, last_name) values (121, 'Maryjo', 'Di Roberto');
insert into authors (id, first_name, last_name) values (122, 'Rogerio', 'Borthe');
insert into authors (id, first_name, last_name) values (123, 'Mikkel', 'Renforth');
insert into authors (id, first_name, last_name) values (124, 'Donaugh', 'Smouten');
insert into authors (id, first_name, last_name) values (125, 'Miguelita', 'Churchman');
insert into authors (id, first_name, last_name) values (126, 'Gaile', 'Tapply');
insert into authors (id, first_name, last_name) values (127, 'Wendi', 'Chopping');
insert into authors (id, first_name, last_name) values (128, 'Shandra', 'Bechley');
insert into authors (id, first_name, last_name) values (129, 'Marven', 'Cavendish');
insert into authors (id, first_name, last_name) values (130, 'Robyn', 'Raye');
insert into authors (id, first_name, last_name) values (131, 'Fayette', 'Isack');
insert into authors (id, first_name, last_name) values (132, 'Joye', 'Westerman');
insert into authors (id, first_name, last_name) values (133, 'Carlina', 'Hentzeler');
insert into authors (id, first_name, last_name) values (134, 'Emogene', 'Blakemore');
insert into authors (id, first_name, last_name) values (135, 'Eugene', 'Manilow');
insert into authors (id, first_name, last_name) values (136, 'Nobie', 'Castella');
insert into authors (id, first_name, last_name) values (137, 'Anna-maria', 'Rainton');
insert into authors (id, first_name, last_name) values (138, 'Elka', 'Loveman');
insert into authors (id, first_name, last_name) values (139, 'Christy', 'Barbary');
insert into authors (id, first_name, last_name) values (140, 'Guthry', 'Lukash');
insert into authors (id, first_name, last_name) values (141, 'Adolphus', 'Flatley');
insert into authors (id, first_name, last_name) values (142, 'Tobias', 'Follows');
insert into authors (id, first_name, last_name) values (143, 'Natassia', 'Rackam');
insert into authors (id, first_name, last_name) values (144, 'Elisha', 'Jakucewicz');
insert into authors (id, first_name, last_name) values (145, 'Lethia', 'Fawkes');
insert into authors (id, first_name, last_name) values (146, 'Fern', 'Gingedale');
insert into authors (id, first_name, last_name) values (147, 'Arly', 'Tizard');
insert into authors (id, first_name, last_name) values (148, 'Henrietta', 'Haymes');
insert into authors (id, first_name, last_name) values (149, 'Theadora', 'Gaye');
insert into authors (id, first_name, last_name) values (150, 'Valida', 'Whitticks');
insert into authors (id, first_name, last_name) values (151, 'Bartholomew', 'Yakovitch');
insert into authors (id, first_name, last_name) values (152, 'Broderick', 'MacGow');
insert into authors (id, first_name, last_name) values (153, 'Moll', 'George');
insert into authors (id, first_name, last_name) values (154, 'Averell', 'Behrens');
insert into authors (id, first_name, last_name) values (155, 'Suellen', 'Wilstead');
insert into authors (id, first_name, last_name) values (156, 'Karita', 'Esel');
insert into authors (id, first_name, last_name) values (157, 'Miriam', 'Murrigan');
insert into authors (id, first_name, last_name) values (158, 'Jobey', 'Batram');
insert into authors (id, first_name, last_name) values (159, 'Ethelred', 'Stedson');
insert into authors (id, first_name, last_name) values (160, 'Christoforo', 'Donativo');
insert into authors (id, first_name, last_name) values (161, 'Terrell', 'Tate');
insert into authors (id, first_name, last_name) values (162, 'Alessandro', 'Hought');
insert into authors (id, first_name, last_name) values (163, 'Hyacintha', 'Guy');
insert into authors (id, first_name, last_name) values (164, 'Tulley', 'Lippard');
insert into authors (id, first_name, last_name) values (165, 'Nataniel', 'Straneo');
insert into authors (id, first_name, last_name) values (166, 'Maxie', 'Whitehorn');
insert into authors (id, first_name, last_name) values (167, 'Jodi', 'Isaak');
insert into authors (id, first_name, last_name) values (168, 'Stillmann', 'Izaac');
insert into authors (id, first_name, last_name) values (169, 'Selene', 'Arnould');
insert into authors (id, first_name, last_name) values (170, 'Murvyn', 'Bradnum');
insert into authors (id, first_name, last_name) values (171, 'Sheilah', 'Strover');
insert into authors (id, first_name, last_name) values (172, 'Kanya', 'O''Crigan');
insert into authors (id, first_name, last_name) values (173, 'Anabal', 'Puddifer');
insert into authors (id, first_name, last_name) values (174, 'Eberhard', 'Peller');
insert into authors (id, first_name, last_name) values (175, 'Fairfax', 'De Ambrosis');
insert into authors (id, first_name, last_name) values (176, 'Mathias', 'Frushard');
insert into authors (id, first_name, last_name) values (177, 'Myrtice', 'MacAndrew');
insert into authors (id, first_name, last_name) values (178, 'Herb', 'Graine');
insert into authors (id, first_name, last_name) values (179, 'Nathanael', 'Effemy');
insert into authors (id, first_name, last_name) values (180, 'Cathleen', 'Matzen');
insert into authors (id, first_name, last_name) values (181, 'Kora', 'Todhunter');
insert into authors (id, first_name, last_name) values (182, 'Thea', 'Banker');
insert into authors (id, first_name, last_name) values (183, 'Doloritas', 'Haxley');
insert into authors (id, first_name, last_name) values (184, 'Brnaba', 'Chantree');
insert into authors (id, first_name, last_name) values (185, 'Nickie', 'Blowen');
insert into authors (id, first_name, last_name) values (186, 'Claudetta', 'Wilsee');
insert into authors (id, first_name, last_name) values (187, 'Ker', 'Claw');
insert into authors (id, first_name, last_name) values (188, 'Shani', 'Stedmond');
insert into authors (id, first_name, last_name) values (189, 'Tymothy', 'Hancox');
insert into authors (id, first_name, last_name) values (190, 'Valina', 'Demcak');
insert into authors (id, first_name, last_name) values (191, 'Bernice', 'Brazier');
insert into authors (id, first_name, last_name) values (192, 'Felicle', 'Giovanazzi');
insert into authors (id, first_name, last_name) values (193, 'Marlena', 'Atthowe');
insert into authors (id, first_name, last_name) values (194, 'Steffane', 'Novotne');
insert into authors (id, first_name, last_name) values (195, 'Corella', 'Sutter');
insert into authors (id, first_name, last_name) values (196, 'Collete', 'Llewellen');
insert into authors (id, first_name, last_name) values (197, 'Chrysler', 'Vials');
insert into authors (id, first_name, last_name) values (198, 'Silva', 'Hearley');
insert into authors (id, first_name, last_name) values (199, 'Federico', 'Cockayne');
insert into authors (id, first_name, last_name) values (200, 'Braden', 'Le Breton');
insert into authors (id, first_name, last_name) values (201, 'Des', 'Sign');
insert into authors (id, first_name, last_name) values (202, 'Valma', 'Ginnety');
insert into authors (id, first_name, last_name) values (203, 'Rhona', 'Whissell');
insert into authors (id, first_name, last_name) values (204, 'Quinn', 'Matthisson');
insert into authors (id, first_name, last_name) values (205, 'Gweneth', 'Corde');
insert into authors (id, first_name, last_name) values (206, 'Isidro', 'Kitchenman');
insert into authors (id, first_name, last_name) values (207, 'Pattie', 'Collyer');
insert into authors (id, first_name, last_name) values (208, 'Ibbie', 'Nafziger');
insert into authors (id, first_name, last_name) values (209, 'Cammie', 'Ambresin');
insert into authors (id, first_name, last_name) values (210, 'Stanislaus', 'Netting');
insert into authors (id, first_name, last_name) values (211, 'Patric', 'Shirtliff');
insert into authors (id, first_name, last_name) values (212, 'Karry', 'Meriel');
insert into authors (id, first_name, last_name) values (213, 'Aylmar', 'Cornish');
insert into authors (id, first_name, last_name) values (214, 'Des', 'Lutty');
insert into authors (id, first_name, last_name) values (215, 'Devin', 'Legges');
insert into authors (id, first_name, last_name) values (216, 'Bennie', 'Pietrasik');
insert into authors (id, first_name, last_name) values (217, 'Callie', 'Hinksen');
insert into authors (id, first_name, last_name) values (218, 'Nonie', 'Peele');
insert into authors (id, first_name, last_name) values (219, 'Rogers', 'Braddon');
insert into authors (id, first_name, last_name) values (220, 'Elbert', 'Cuffley');
insert into authors (id, first_name, last_name) values (221, 'Zechariah', 'Quogan');
insert into authors (id, first_name, last_name) values (222, 'Natalya', 'Barnet');
insert into authors (id, first_name, last_name) values (223, 'Tremain', 'Driffill');
insert into authors (id, first_name, last_name) values (224, 'Arlena', 'Rown');
insert into authors (id, first_name, last_name) values (225, 'Laina', 'Croutear');
insert into authors (id, first_name, last_name) values (226, 'Doug', 'Sidnell');
insert into authors (id, first_name, last_name) values (227, 'Arluene', 'Ranns');
insert into authors (id, first_name, last_name) values (228, 'Harlie', 'Cancellor');
insert into authors (id, first_name, last_name) values (229, 'Raffaello', 'Dalloway');
insert into authors (id, first_name, last_name) values (230, 'Theodoric', 'Rash');
insert into authors (id, first_name, last_name) values (231, 'Diarmid', 'Matus');
insert into authors (id, first_name, last_name) values (232, 'Tobe', 'Beardsall');
insert into authors (id, first_name, last_name) values (233, 'Noelle', 'Micklewright');
insert into authors (id, first_name, last_name) values (234, 'Leontine', 'Brewitt');
insert into authors (id, first_name, last_name) values (235, 'Francine', 'Auletta');
insert into authors (id, first_name, last_name) values (236, 'Anthea', 'Abelwhite');
insert into authors (id, first_name, last_name) values (237, 'Izaak', 'Toderi');
insert into authors (id, first_name, last_name) values (238, 'Correy', 'Merigot');
insert into authors (id, first_name, last_name) values (239, 'Mikol', 'Greatex');
insert into authors (id, first_name, last_name) values (240, 'Reg', 'Eskriet');
insert into authors (id, first_name, last_name) values (241, 'Clemens', 'Balazot');
insert into authors (id, first_name, last_name) values (242, 'Lanette', 'Butterfield');
insert into authors (id, first_name, last_name) values (243, 'Fulton', 'Yon');
insert into authors (id, first_name, last_name) values (244, 'Shane', 'Klimentyonok');
insert into authors (id, first_name, last_name) values (245, 'Waverly', 'Ivchenko');
insert into authors (id, first_name, last_name) values (246, 'Thorin', 'Waddoups');
insert into authors (id, first_name, last_name) values (247, 'Bald', 'Gollop');
insert into authors (id, first_name, last_name) values (248, 'Harri', 'Kingman');
insert into authors (id, first_name, last_name) values (249, 'Nicolas', 'Ollivier');
insert into authors (id, first_name, last_name) values (250, 'Red', 'Spelwood');
insert into authors (id, first_name, last_name) values (251, 'Phillipp', 'Aylen');
insert into authors (id, first_name, last_name) values (252, 'Bibbie', 'Inglese');
insert into authors (id, first_name, last_name) values (253, 'Rita', 'Tarbox');
insert into authors (id, first_name, last_name) values (254, 'Sophronia', 'Curmi');
insert into authors (id, first_name, last_name) values (255, 'Helaina', 'Harburtson');
insert into authors (id, first_name, last_name) values (256, 'Olympe', 'Ferraretto');
insert into authors (id, first_name, last_name) values (257, 'Valry', 'Asch');
insert into authors (id, first_name, last_name) values (258, 'Torin', 'Toovey');
insert into authors (id, first_name, last_name) values (259, 'Almire', 'Fantin');
insert into authors (id, first_name, last_name) values (260, 'Sarajane', 'Wackley');
insert into authors (id, first_name, last_name) values (261, 'Dyane', 'Sibylla');
insert into authors (id, first_name, last_name) values (262, 'Freida', 'Jillis');
insert into authors (id, first_name, last_name) values (263, 'Jermain', 'Middis');
insert into authors (id, first_name, last_name) values (264, 'Holt', 'Moogan');
insert into authors (id, first_name, last_name) values (265, 'Britteny', 'Sinkinson');
insert into authors (id, first_name, last_name) values (266, 'Felita', 'Prattin');
insert into authors (id, first_name, last_name) values (267, 'Sasha', 'Nicholson');
insert into authors (id, first_name, last_name) values (268, 'Mikel', 'Coomes');
insert into authors (id, first_name, last_name) values (269, 'Paul', 'Dies');
insert into authors (id, first_name, last_name) values (270, 'Claus', 'Forsard');
insert into authors (id, first_name, last_name) values (271, 'Orlando', 'Wozencraft');
insert into authors (id, first_name, last_name) values (272, 'Dieter', 'Strooband');
insert into authors (id, first_name, last_name) values (273, 'Emmi', 'Keats');
insert into authors (id, first_name, last_name) values (274, 'Ada', 'Teggin');
insert into authors (id, first_name, last_name) values (275, 'Ivonne', 'Janik');
insert into authors (id, first_name, last_name) values (276, 'Laney', 'Fairburne');
insert into authors (id, first_name, last_name) values (277, 'Massimiliano', 'Kittow');
insert into authors (id, first_name, last_name) values (278, 'Feodor', 'MacDowal');
insert into authors (id, first_name, last_name) values (279, 'Maryjo', 'Comber');
insert into authors (id, first_name, last_name) values (280, 'Zarla', 'Thomtson');
insert into authors (id, first_name, last_name) values (281, 'Wait', 'Pales');
insert into authors (id, first_name, last_name) values (282, 'Morlee', 'Vanni');
insert into authors (id, first_name, last_name) values (283, 'Jodie', 'Coonihan');
insert into authors (id, first_name, last_name) values (284, 'Kay', 'Fransinelli');
insert into authors (id, first_name, last_name) values (285, 'Gayler', 'Forsaith');
insert into authors (id, first_name, last_name) values (286, 'Fran', 'Melson');
insert into authors (id, first_name, last_name) values (287, 'Philis', 'Avramchik');
insert into authors (id, first_name, last_name) values (288, 'Gian', 'Bromley');
insert into authors (id, first_name, last_name) values (289, 'Doralia', 'Spraggs');
insert into authors (id, first_name, last_name) values (290, 'Dagmar', 'Rothermel');
insert into authors (id, first_name, last_name) values (291, 'Walliw', 'Mattke');
insert into authors (id, first_name, last_name) values (292, 'Mel', 'Mooreed');
insert into authors (id, first_name, last_name) values (293, 'Wendie', 'Antcliff');
insert into authors (id, first_name, last_name) values (294, 'Fairlie', 'Saltwell');
insert into authors (id, first_name, last_name) values (295, 'Sibel', 'Loudyan');
insert into authors (id, first_name, last_name) values (296, 'Bernardine', 'Rawlence');
insert into authors (id, first_name, last_name) values (297, 'Dominick', 'Lamperd');
insert into authors (id, first_name, last_name) values (298, 'Isobel', 'Burchell');
insert into authors (id, first_name, last_name) values (299, 'Sophie', 'Hunnicot');
insert into authors (id, first_name, last_name) values (300, 'Sharity', 'Paladini');
insert into authors (id, first_name, last_name) values (301, 'Grove', 'Tarbert');
insert into authors (id, first_name, last_name) values (302, 'Tremayne', 'Pickance');
insert into authors (id, first_name, last_name) values (303, 'Riva', 'Alloway');
insert into authors (id, first_name, last_name) values (304, 'Karney', 'Dodsley');
insert into authors (id, first_name, last_name) values (305, 'Rodge', 'Morena');
insert into authors (id, first_name, last_name) values (306, 'Cherin', 'Soanes');
insert into authors (id, first_name, last_name) values (307, 'Morgun', 'Wallice');
insert into authors (id, first_name, last_name) values (308, 'Geraldine', 'Leverich');
insert into authors (id, first_name, last_name) values (309, 'Katalin', 'Kneale');
insert into authors (id, first_name, last_name) values (310, 'Daisy', 'Hawson');
insert into authors (id, first_name, last_name) values (311, 'Gaspard', 'Dommerque');
insert into authors (id, first_name, last_name) values (312, 'Ibby', 'Halle');
insert into authors (id, first_name, last_name) values (313, 'Anica', 'Jerzyk');
insert into authors (id, first_name, last_name) values (314, 'Nikolaus', 'Aldritt');
insert into authors (id, first_name, last_name) values (315, 'Brandie', 'Kean');
insert into authors (id, first_name, last_name) values (316, 'Willem', 'Elstub');
insert into authors (id, first_name, last_name) values (317, 'Trudy', 'Gornall');
insert into authors (id, first_name, last_name) values (318, 'Nannie', 'Holttom');
insert into authors (id, first_name, last_name) values (319, 'Ursula', 'Bungey');
insert into authors (id, first_name, last_name) values (320, 'Gusta', 'Skirling');
insert into authors (id, first_name, last_name) values (321, 'Camellia', 'Costar');
insert into authors (id, first_name, last_name) values (322, 'Rena', 'Bryns');
insert into authors (id, first_name, last_name) values (323, 'Broderic', 'Hamm');
insert into authors (id, first_name, last_name) values (324, 'Franchot', 'Stairmond');
insert into authors (id, first_name, last_name) values (325, 'Cathleen', 'Bunkle');
insert into authors (id, first_name, last_name) values (326, 'Agnella', 'Coggan');
insert into authors (id, first_name, last_name) values (327, 'Lisette', 'Durie');
insert into authors (id, first_name, last_name) values (328, 'Issi', 'Goult');
insert into authors (id, first_name, last_name) values (329, 'Bernadina', 'Caslett');
insert into authors (id, first_name, last_name) values (330, 'Modesty', 'Whitwham');
insert into authors (id, first_name, last_name) values (331, 'Lillian', 'Seton');
insert into authors (id, first_name, last_name) values (332, 'Mead', 'Anten');
insert into authors (id, first_name, last_name) values (333, 'Rayna', 'Bottomore');
insert into authors (id, first_name, last_name) values (334, 'Carmelle', 'Osgorby');
insert into authors (id, first_name, last_name) values (335, 'Bevvy', 'Keuneke');
insert into authors (id, first_name, last_name) values (336, 'Jeniece', 'Ubanks');
insert into authors (id, first_name, last_name) values (337, 'Roderich', 'Thiolier');
insert into authors (id, first_name, last_name) values (338, 'Daphne', 'D''Antoni');
insert into authors (id, first_name, last_name) values (339, 'Marena', 'Knagges');
insert into authors (id, first_name, last_name) values (340, 'Linnie', 'Dachs');
insert into authors (id, first_name, last_name) values (341, 'Germain', 'Petrie');
insert into authors (id, first_name, last_name) values (342, 'Mollee', 'Cassey');
insert into authors (id, first_name, last_name) values (343, 'Seka', 'Gislebert');
insert into authors (id, first_name, last_name) values (344, 'Celie', 'Austen');
insert into authors (id, first_name, last_name) values (345, 'Merralee', 'McLennan');
insert into authors (id, first_name, last_name) values (346, 'Cathy', 'Lander');
insert into authors (id, first_name, last_name) values (347, 'Hope', 'Greenfield');
insert into authors (id, first_name, last_name) values (348, 'Natale', 'Stathers');
insert into authors (id, first_name, last_name) values (349, 'Lisette', 'Jeacock');
insert into authors (id, first_name, last_name) values (350, 'Matt', 'Capun');
insert into authors (id, first_name, last_name) values (351, 'Beauregard', 'Seaward');
insert into authors (id, first_name, last_name) values (352, 'Homerus', 'O''Hickey');
insert into authors (id, first_name, last_name) values (353, 'Sandye', 'McCathy');
insert into authors (id, first_name, last_name) values (354, 'Cosette', 'Bratten');
insert into authors (id, first_name, last_name) values (355, 'Merridie', 'Dominiak');
insert into authors (id, first_name, last_name) values (356, 'Helaina', 'Panner');
insert into authors (id, first_name, last_name) values (357, 'Sherry', 'Stains');
insert into authors (id, first_name, last_name) values (358, 'Friedrick', 'Joseph');
insert into authors (id, first_name, last_name) values (359, 'Wallas', 'Korneluk');
insert into authors (id, first_name, last_name) values (360, 'Holt', 'Goade');
insert into authors (id, first_name, last_name) values (361, 'Evania', 'Nel');
insert into authors (id, first_name, last_name) values (362, 'Rikki', 'Wicks');
insert into authors (id, first_name, last_name) values (363, 'Susan', 'Lody');
insert into authors (id, first_name, last_name) values (364, 'Marcelo', 'O''Longain');
insert into authors (id, first_name, last_name) values (365, 'Teirtza', 'Doick');
insert into authors (id, first_name, last_name) values (366, 'Sigfrid', 'Follan');
insert into authors (id, first_name, last_name) values (367, 'Steffie', 'Klimczak');
insert into authors (id, first_name, last_name) values (368, 'Shoshana', 'Craigg');
insert into authors (id, first_name, last_name) values (369, 'Heidi', 'Pritchett');
insert into authors (id, first_name, last_name) values (370, 'Alexio', 'Tomaszek');
insert into authors (id, first_name, last_name) values (371, 'Bernadette', 'Dunckley');
insert into authors (id, first_name, last_name) values (372, 'Catharina', 'McCalister');
insert into authors (id, first_name, last_name) values (373, 'Louise', 'Pickover');
insert into authors (id, first_name, last_name) values (374, 'Anselm', 'Antonellini');
insert into authors (id, first_name, last_name) values (375, 'Meg', 'Woliter');
insert into authors (id, first_name, last_name) values (376, 'Amaleta', 'Wapol');
insert into authors (id, first_name, last_name) values (377, 'Ansell', 'Dearlove');
insert into authors (id, first_name, last_name) values (378, 'Corbett', 'McKennan');
insert into authors (id, first_name, last_name) values (379, 'Patty', 'Lapish');
insert into authors (id, first_name, last_name) values (380, 'Myriam', 'Denacamp');
insert into authors (id, first_name, last_name) values (381, 'Sergeant', 'Jelliman');
insert into authors (id, first_name, last_name) values (382, 'Tyrone', 'Roblin');
insert into authors (id, first_name, last_name) values (383, 'Cly', 'Santacrole');
insert into authors (id, first_name, last_name) values (384, 'Madge', 'Kyncl');
insert into authors (id, first_name, last_name) values (385, 'Fritz', 'Anespie');
insert into authors (id, first_name, last_name) values (386, 'Cori', 'Haynesford');
insert into authors (id, first_name, last_name) values (387, 'Marja', 'Narracott');
insert into authors (id, first_name, last_name) values (388, 'Gerri', 'Hazelden');
insert into authors (id, first_name, last_name) values (389, 'Lorette', 'Skellon');
insert into authors (id, first_name, last_name) values (390, 'Keslie', 'Hinstock');
insert into authors (id, first_name, last_name) values (391, 'Evelyn', 'Harman');
insert into authors (id, first_name, last_name) values (392, 'Damiano', 'Awin');
insert into authors (id, first_name, last_name) values (393, 'Kassandra', 'Boat');
insert into authors (id, first_name, last_name) values (394, 'Lockwood', 'Belliveau');
insert into authors (id, first_name, last_name) values (395, 'Marianne', 'Seston');
insert into authors (id, first_name, last_name) values (396, 'Curry', 'Crossley');
insert into authors (id, first_name, last_name) values (397, 'Margie', 'Danilchev');
insert into authors (id, first_name, last_name) values (398, 'Gwyn', 'Cartmael');
insert into authors (id, first_name, last_name) values (399, 'Millie', 'MacCulloch');
insert into authors (id, first_name, last_name) values (400, 'Amalie', 'Colyer');
insert into authors (id, first_name, last_name) values (401, 'Gregor', 'Farington');
insert into authors (id, first_name, last_name) values (402, 'Davis', 'Petriello');
insert into authors (id, first_name, last_name) values (403, 'Athena', 'Garstan');
insert into authors (id, first_name, last_name) values (404, 'Myca', 'Fetters');
insert into authors (id, first_name, last_name) values (405, 'Ara', 'Alentyev');
insert into authors (id, first_name, last_name) values (406, 'Marcos', 'Darrington');
insert into authors (id, first_name, last_name) values (407, 'Corene', 'Yusupov');
insert into authors (id, first_name, last_name) values (408, 'Corliss', 'Galliford');
insert into authors (id, first_name, last_name) values (409, 'Renaldo', 'Bloys');
insert into authors (id, first_name, last_name) values (410, 'Si', 'Christaeas');
insert into authors (id, first_name, last_name) values (411, 'Ardys', 'Keyser');
insert into authors (id, first_name, last_name) values (412, 'Clotilda', 'Rennels');
insert into authors (id, first_name, last_name) values (413, 'Diane-marie', 'Toupe');
insert into authors (id, first_name, last_name) values (414, 'Agneta', 'Whalebelly');
insert into authors (id, first_name, last_name) values (415, 'Rey', 'Tetford');
insert into authors (id, first_name, last_name) values (416, 'Bertha', 'Basili');
insert into authors (id, first_name, last_name) values (417, 'Stacee', 'Housbie');
insert into authors (id, first_name, last_name) values (418, 'Anatola', 'Montez');
insert into authors (id, first_name, last_name) values (419, 'Granthem', 'Anders');
insert into authors (id, first_name, last_name) values (420, 'Berkie', 'Dyke');
insert into authors (id, first_name, last_name) values (421, 'Francine', 'Fallow');
insert into authors (id, first_name, last_name) values (422, 'Gerrard', 'Abele');
insert into authors (id, first_name, last_name) values (423, 'Newton', 'Bruckshaw');
insert into authors (id, first_name, last_name) values (424, 'Kermie', 'Culvey');
insert into authors (id, first_name, last_name) values (425, 'Karoly', 'Gyorffy');
insert into authors (id, first_name, last_name) values (426, 'Teresita', 'Bodleigh');
insert into authors (id, first_name, last_name) values (427, 'Loise', 'Bernet');
insert into authors (id, first_name, last_name) values (428, 'Jonis', 'Agnolo');
insert into authors (id, first_name, last_name) values (429, 'Katuscha', 'Swinfen');
insert into authors (id, first_name, last_name) values (430, 'Timmi', 'Stokey');
insert into authors (id, first_name, last_name) values (431, 'Berenice', 'Gerard');
insert into authors (id, first_name, last_name) values (432, 'Rab', 'Jerromes');
insert into authors (id, first_name, last_name) values (433, 'Sukey', 'Tournay');
insert into authors (id, first_name, last_name) values (434, 'Diana', 'Batty');
insert into authors (id, first_name, last_name) values (435, 'Rupert', 'Ockendon');
insert into authors (id, first_name, last_name) values (436, 'Lyndel', 'Bellino');
insert into authors (id, first_name, last_name) values (437, 'Georgeanne', 'Flaws');
insert into authors (id, first_name, last_name) values (438, 'Mendy', 'Robertson');
insert into authors (id, first_name, last_name) values (439, 'Johann', 'Massey');
insert into authors (id, first_name, last_name) values (440, 'Gusti', 'Jennick');
insert into authors (id, first_name, last_name) values (441, 'Dede', 'Yole');
insert into authors (id, first_name, last_name) values (442, 'Ax', 'Brombell');
insert into authors (id, first_name, last_name) values (443, 'Berkie', 'Demelt');
insert into authors (id, first_name, last_name) values (444, 'Tobie', 'Colbourne');
insert into authors (id, first_name, last_name) values (445, 'Bevan', 'Gratton');
insert into authors (id, first_name, last_name) values (446, 'Rene', 'Braden');
insert into authors (id, first_name, last_name) values (447, 'Annabal', 'Le Leu');
insert into authors (id, first_name, last_name) values (448, 'Ardeen', 'Restill');
insert into authors (id, first_name, last_name) values (449, 'Jordan', 'Nial');
insert into authors (id, first_name, last_name) values (450, 'Aleece', 'Sherme');
insert into authors (id, first_name, last_name) values (451, 'Bette', 'Agerskow');
insert into authors (id, first_name, last_name) values (452, 'Daisi', 'Dalman');
insert into authors (id, first_name, last_name) values (453, 'Maxine', 'Fawson');
insert into authors (id, first_name, last_name) values (454, 'Milty', 'Clemoes');
insert into authors (id, first_name, last_name) values (455, 'Sallyann', 'Doumerc');
insert into authors (id, first_name, last_name) values (456, 'Gavan', 'Furnell');
insert into authors (id, first_name, last_name) values (457, 'Terese', 'Marl');
insert into authors (id, first_name, last_name) values (458, 'Crichton', 'Sieve');
insert into authors (id, first_name, last_name) values (459, 'Aloysius', 'Tyrrell');
insert into authors (id, first_name, last_name) values (460, 'Cathee', 'Kibbey');
insert into authors (id, first_name, last_name) values (461, 'Baudoin', 'Behning');
insert into authors (id, first_name, last_name) values (462, 'Torey', 'Fegan');
insert into authors (id, first_name, last_name) values (463, 'Diane', 'Doctor');
insert into authors (id, first_name, last_name) values (464, 'Winny', 'Macbeth');
insert into authors (id, first_name, last_name) values (465, 'Batsheva', 'Vanyarkin');
insert into authors (id, first_name, last_name) values (466, 'Sterling', 'Jakubski');
insert into authors (id, first_name, last_name) values (467, 'Tuesday', 'Matteau');
insert into authors (id, first_name, last_name) values (468, 'Maddalena', 'Filippozzi');
insert into authors (id, first_name, last_name) values (469, 'Hailey', 'Watmough');
insert into authors (id, first_name, last_name) values (470, 'Carlotta', 'Kearford');
insert into authors (id, first_name, last_name) values (471, 'Maryellen', 'Master');
insert into authors (id, first_name, last_name) values (472, 'Hillyer', 'Douty');
insert into authors (id, first_name, last_name) values (473, 'Leland', 'Hovenden');
insert into authors (id, first_name, last_name) values (474, 'Drusie', 'Coch');
insert into authors (id, first_name, last_name) values (475, 'Ole', 'Eringey');
insert into authors (id, first_name, last_name) values (476, 'Iorgo', 'Wanklyn');
insert into authors (id, first_name, last_name) values (477, 'Hoyt', 'Eccleston');
insert into authors (id, first_name, last_name) values (478, 'Gustavo', 'Eade');
insert into authors (id, first_name, last_name) values (479, 'Jeth', 'Estcourt');
insert into authors (id, first_name, last_name) values (480, 'Thibaud', 'Qualtro');
insert into authors (id, first_name, last_name) values (481, 'Lanae', 'Ayliffe');
insert into authors (id, first_name, last_name) values (482, 'Hermine', 'Theyer');
insert into authors (id, first_name, last_name) values (483, 'Leanora', 'Skein');
insert into authors (id, first_name, last_name) values (484, 'Major', 'Layton');
insert into authors (id, first_name, last_name) values (485, 'Brooke', 'Cavendish');
insert into authors (id, first_name, last_name) values (486, 'Fraze', 'Dudbridge');
insert into authors (id, first_name, last_name) values (487, 'Guillemette', 'Grundey');
insert into authors (id, first_name, last_name) values (488, 'Teresina', 'Preon');
insert into authors (id, first_name, last_name) values (489, 'Carrie', 'Yushachkov');
insert into authors (id, first_name, last_name) values (490, 'Juana', 'Valdes');
insert into authors (id, first_name, last_name) values (491, 'Inigo', 'Ablewhite');
insert into authors (id, first_name, last_name) values (492, 'Ginger', 'Tallis');
insert into authors (id, first_name, last_name) values (493, 'Mycah', 'Hemmingway');
insert into authors (id, first_name, last_name) values (494, 'Kipper', 'Teideman');
insert into authors (id, first_name, last_name) values (495, 'Clari', 'Bovaird');
insert into authors (id, first_name, last_name) values (496, 'Eugenie', 'Turn');
insert into authors (id, first_name, last_name) values (497, 'Felizio', 'Ffrench');
insert into authors (id, first_name, last_name) values (498, 'Pasquale', 'Roz');
insert into authors (id, first_name, last_name) values (499, 'Gerard', 'Askam');
insert into authors (id, first_name, last_name) values (500, 'Gasper', 'Buddock');



insert into books (id, author_id, title, price_old, price) values (1, 366, 'Dry Summer ', '$205.12', '$192.02');
insert into books (id, author_id, title, price_old, price) values (2, 498, 'Terrible Kids', '$35.00', '$9.75');
insert into books (id, author_id, title, price_old, price) values (3, 268, 'Fear and Desire', '$99.64', '$235.96');
insert into books (id, author_id, title, price_old, price) values (4, 365, 'Gallowwalkers', '$182.19', '$46.82');
insert into books (id, author_id, title, price_old, price) values (5, 181, 'Great Ecstasy of Woodcarver Steiner, The ', '$248.14', '$134.42');
insert into books (id, author_id, title, price_old, price) values (6, 54, 'Last Hurrah for Chivalry', '$145.89', '$70.36');
insert into books (id, author_id, title, price_old, price) values (7, 26, 'Hard Ticket to Hawaii', '$241.39', '$89.34');
insert into books (id, author_id, title, price_old, price) values (8, 305, 'The Identical', '$132.02', '$5.94');
insert into books (id, author_id, title, price_old, price) values (9, 44, 'The Retrieval', '$42.69', '$244.86');
insert into books (id, author_id, title, price_old, price) values (10, 193, 'Saawariya', '$103.77', '$186.40');
insert into books (id, author_id, title, price_old, price) values (11, 329, 'Love and Pigeons', '$147.88', '$73.79');
insert into books (id, author_id, title, price_old, price) values (12, 269, 'You Can Count on Me', '$206.63', '$160.64');
insert into books (id, author_id, title, price_old, price) values (13, 459, 'Pericles on 31st Street', '$196.74', '$179.34');
insert into books (id, author_id, title, price_old, price) values (14, 83, 'Thor: Tales of Asgard', '$131.57', '$247.59');
insert into books (id, author_id, title, price_old, price) values (15, 347, '99 River Street', '$207.39', '$166.30');
insert into books (id, author_id, title, price_old, price) values (16, 59, 'Of Freaks and Men', '$147.95', '$14.21');
insert into books (id, author_id, title, price_old, price) values (17, 327, 'Village of the Giants', '$218.14', '$19.77');
insert into books (id, author_id, title, price_old, price) values (18, 66, 'Three Smart Girls', '$22.86', '$103.34');
insert into books (id, author_id, title, price_old, price) values (19, 345, 'Vampires Suck', '$171.83', '$99.63');
insert into books (id, author_id, title, price_old, price) values (20, 213, 'Small Roads', '$140.42', '$108.52');
insert into books (id, author_id, title, price_old, price) values (21, 390, 'My Own Private Idaho', '$92.93', '$197.19');
insert into books (id, author_id, title, price_old, price) values (22, 468, 'Asterix in America', '$82.47', '$111.47');
insert into books (id, author_id, title, price_old, price) values (23, 360, 'The Chaos Class Failed the Class', '$80.34', '$5.91');
insert into books (id, author_id, title, price_old, price) values (24, 294, 'Bundle of Joy', '$175.45', '$55.65');
insert into books (id, author_id, title, price_old, price) values (25, 98, 'You Kill Me', '$59.42', '$79.93');
insert into books (id, author_id, title, price_old, price) values (26, 103, 'Maya Lin: A Strong Clear Vision', '$233.44', '$119.94');
insert into books (id, author_id, title, price_old, price) values (27, 127, 'Joan of Arc', '$40.72', '$184.01');
insert into books (id, author_id, title, price_old, price) values (28, 30, 'Pekka ja', '$230.51', '$202.23');
insert into books (id, author_id, title, price_old, price) values (29, 324, '2 Days in the Valley', '$219.93', '$118.60');
insert into books (id, author_id, title, price_old, price) values (30, 149, 'Chicago Overcoat', '$147.78', '$166.85');
insert into books (id, author_id, title, price_old, price) values (31, 191, 'Shopgirl', '$45.11', '$157.73');
insert into books (id, author_id, title, price_old, price) values (32, 466, 'Countess Dracula', '$13.32', '$184.93');
insert into books (id, author_id, title, price_old, price) values (33, 81, 'Blueprint for Murder, A', '$175.27', '$88.55');
insert into books (id, author_id, title, price_old, price) values (34, 262, 'Joe Dirt', '$140.52', '$57.93');
insert into books (id, author_id, title, price_old, price) values (35, 284, 'Chaos', '$186.11', '$156.47');
insert into books (id, author_id, title, price_old, price) values (36, 498, 'Hotel New Hampshire, The', '$244.88', '$224.76');
insert into books (id, author_id, title, price_old, price) values (37, 204, 'John Garfield Story, The', '$48.18', '$87.58');
insert into books (id, author_id, title, price_old, price) values (38, 81, 'Mitt', '$114.66', '$99.34');
insert into books (id, author_id, title, price_old, price) values (39, 244, 'Radio Inside', '$192.85', '$188.09');
insert into books (id, author_id, title, price_old, price) values (40, 131, 'Hiding Out', '$223.65', '$62.29');
insert into books (id, author_id, title, price_old, price) values (41, 468, 'Me Myself I', '$92.87', '$90.99');
insert into books (id, author_id, title, price_old, price) values (42, 341, 'Cloudy with a Chance of Meatballs', '$210.48', '$66.04');
insert into books (id, author_id, title, price_old, price) values (43, 196, 'Kit Kittredge: An American Girl', '$249.51', '$243.39');
insert into books (id, author_id, title, price_old, price) values (44, 77, 'Mean Girls 2', '$83.90', '$234.67');
insert into books (id, author_id, title, price_old, price) values (45, 412, 'The Hire: Star, The', '$60.43', '$12.90');
insert into books (id, author_id, title, price_old, price) values (46, 236, 'Brooklyn Castle', '$1.31', '$157.14');
insert into books (id, author_id, title, price_old, price) values (47, 396, 'The Island', '$133.87', '$193.02');
insert into books (id, author_id, title, price_old, price) values (48, 458, 'DNA', '$95.52', '$25.44');
insert into books (id, author_id, title, price_old, price) values (49, 19, 'Hellboy', '$120.29', '$79.20');
insert into books (id, author_id, title, price_old, price) values (50, 45, 'Water-mirror of Granada', '$173.59', '$2.49');
insert into books (id, author_id, title, price_old, price) values (51, 347, 'Devils Advocate, The', '$159.24', '$216.86');
insert into books (id, author_id, title, price_old, price) values (52, 160, 'Within Our Gates', '$10.05', '$233.03');
insert into books (id, author_id, title, price_old, price) values (53, 26, 'Situation, The', '$54.34', '$0.97');
insert into books (id, author_id, title, price_old, price) values (54, 159, 'Beast Must Die, The', '$233.93', '$74.28');
insert into books (id, author_id, title, price_old, price) values (55, 419, 'Murderous Maids', '$56.80', '$22.60');
insert into books (id, author_id, title, price_old, price) values (56, 353, 'Tales of the Grim Sleeper', '$241.45', '$195.74');
insert into books (id, author_id, title, price_old, price) values (57, 268, 'Born Free', '$5.61', '$42.00');
insert into books (id, author_id, title, price_old, price) values (58, 106, 'Monica Z', '$122.45', '$191.99');
insert into books (id, author_id, title, price_old, price) values (59, 413, 'Popcorn', '$238.77', '$41.04');
insert into books (id, author_id, title, price_old, price) values (60, 221, 'Wicker Man, The', '$226.47', '$178.38');
insert into books (id, author_id, title, price_old, price) values (61, 216, 'Nymphomaniac: Volume II', '$216.22', '$187.30');
insert into books (id, author_id, title, price_old, price) values (62, 119, 'Red Dust', '$223.58', '$234.94');
insert into books (id, author_id, title, price_old, price) values (63, 157, 'Double Indemnity', '$143.89', '$105.80');
insert into books (id, author_id, title, price_old, price) values (64, 124, 'Blot, The', '$150.71', '$80.37');
insert into books (id, author_id, title, price_old, price) values (65, 263, 'Dead Like Me: Life After Death', '$118.34', '$34.03');
insert into books (id, author_id, title, price_old, price) values (66, 433, 'Place in the Sun, A', '$135.76', '$14.05');
insert into books (id, author_id, title, price_old, price) values (67, 91, 'Eye In The Sky', '$69.74', '$0.09');
insert into books (id, author_id, title, price_old, price) values (68, 463, 'Unfinished Piece for a Player Piano', '$83.79', '$201.53');
insert into books (id, author_id, title, price_old, price) values (69, 477, 'Cameron''s Closet', '$241.98', '$205.11');
insert into books (id, author_id, title, price_old, price) values (70, 392, 'Right Stuff, The', '$118.73', '$155.84');
insert into books (id, author_id, title, price_old, price) values (71, 86, 'Ragnarok', '$43.52', '$228.81');
insert into books (id, author_id, title, price_old, price) values (72, 394, 'By the Law', '$223.73', '$84.28');
insert into books (id, author_id, title, price_old, price) values (73, 416, 'Quality Street', '$71.68', '$200.14');
insert into books (id, author_id, title, price_old, price) values (74, 224, 'Night Listener, The', '$146.73', '$141.40');
insert into books (id, author_id, title, price_old, price) values (75, 241, 'Cobb', '$224.17', '$218.89');
insert into books (id, author_id, title, price_old, price) values (76, 88, 'Bonhoeffer: Agent of Grace', '$127.96', '$1.39');
insert into books (id, author_id, title, price_old, price) values (77, 274, 'Music in the Air', '$13.27', '$202.20');
insert into books (id, author_id, title, price_old, price) values (78, 193, 'In Her Shoes', '$234.59', '$65.08');
insert into books (id, author_id, title, price_old, price) values (79, 426, 'Bean', '$10.76', '$156.15');
insert into books (id, author_id, title, price_old, price) values (80, 375, 'Young Ones', '$26.10', '$164.42');
insert into books (id, author_id, title, price_old, price) values (81, 270, 'All of Me', '$80.50', '$200.67');
insert into books (id, author_id, title, price_old, price) values (82, 135, 'Hungry for Change', '$12.94', '$11.44');
insert into books (id, author_id, title, price_old, price) values (83, 78, 'Doghouse', '$0.51', '$86.93');
insert into books (id, author_id, title, price_old, price) values (84, 484, 'Den, The', '$2.46', '$172.70');
insert into books (id, author_id, title, price_old, price) values (85, 434, 'Poto and Cabengo', '$86.47', '$195.17');
insert into books (id, author_id, title, price_old, price) values (86, 145, 'Andalusian Dog', '$226.29', '$249.96');
insert into books (id, author_id, title, price_old, price) values (87, 483, 'By the Sword', '$98.56', '$50.72');
insert into books (id, author_id, title, price_old, price) values (88, 461, 'Call of the Wild, The', '$122.51', '$24.66');
insert into books (id, author_id, title, price_old, price) values (89, 307, 'Act of Violence', '$109.63', '$97.79');
insert into books (id, author_id, title, price_old, price) values (90, 467, 'Beaufort', '$44.81', '$60.10');
insert into books (id, author_id, title, price_old, price) values (91, 156, 'Eye for an Eye', '$32.33', '$134.48');
insert into books (id, author_id, title, price_old, price) values (92, 372, 'Wanda', '$48.73', '$131.67');
insert into books (id, author_id, title, price_old, price) values (93, 265, 'Old Men in New Cars', '$164.09', '$91.16');
insert into books (id, author_id, title, price_old, price) values (94, 171, 'Orders to Kill', '$184.21', '$213.58');
insert into books (id, author_id, title, price_old, price) values (95, 480, 'Soft Skin, The', '$124.03', '$107.35');
insert into books (id, author_id, title, price_old, price) values (96, 362, 'Lakota Woman: Siege at Wounded Knee', '$78.71', '$187.07');
insert into books (id, author_id, title, price_old, price) values (97, 484, 'Mass Transit', '$173.36', '$26.90');
insert into books (id, author_id, title, price_old, price) values (98, 308, 'Jim Norton: Please Be Offended', '$17.39', '$215.70');
insert into books (id, author_id, title, price_old, price) values (99, 214, 'Mr. Wrong', '$168.84', '$176.21');
insert into books (id, author_id, title, price_old, price) values (100, 33, 'One-Eyed Monster', '$210.56', '$211.87');
insert into books (id, author_id, title, price_old, price) values (101, 351, 'Ministry of Fear', '$248.87', '$132.27');
insert into books (id, author_id, title, price_old, price) values (102, 324, 'Computer Wore Tennis Shoes, The', '$206.65', '$95.13');
insert into books (id, author_id, title, price_old, price) values (103, 410, 'Evil Remains', '$78.42', '$40.78');
insert into books (id, author_id, title, price_old, price) values (104, 327, 'Paperman', '$83.86', '$81.81');
insert into books (id, author_id, title, price_old, price) values (105, 288, 'Our Man in Havana', '$220.75', '$15.14');
insert into books (id, author_id, title, price_old, price) values (106, 49, 'Bubble', '$24.72', '$153.32');
insert into books (id, author_id, title, price_old, price) values (107, 63, 'Woman, The', '$112.29', '$49.39');
insert into books (id, author_id, title, price_old, price) values (108, 435, 'Opera', '$225.76', '$46.13');
insert into books (id, author_id, title, price_old, price) values (109, 117, 'French Fried Vacation 2', '$167.07', '$236.64');
insert into books (id, author_id, title, price_old, price) values (110, 461, 'Crimson Petal and the White, The', '$178.65', '$84.06');
insert into books (id, author_id, title, price_old, price) values (111, 112, 'Stigmata', '$101.52', '$90.47');
insert into books (id, author_id, title, price_old, price) values (112, 152, 'Texas', '$193.35', '$2.63');
insert into books (id, author_id, title, price_old, price) values (113, 266, 'Cradle Will Rock', '$193.66', '$91.65');
insert into books (id, author_id, title, price_old, price) values (114, 302, 'Red Shoes, The', '$75.75', '$163.16');
insert into books (id, author_id, title, price_old, price) values (115, 233, 'Head Office', '$19.39', '$56.74');
insert into books (id, author_id, title, price_old, price) values (116, 189, 'Woochi: The Demon Slayer', '$170.78', '$185.91');
insert into books (id, author_id, title, price_old, price) values (117, 226, 'Alien Autopsy', '$52.28', '$7.65');
insert into books (id, author_id, title, price_old, price) values (118, 386, 'Brooklyn Rules', '$213.59', '$18.10');
insert into books (id, author_id, title, price_old, price) values (119, 223, 'Generals Daughter, The', '$21.98', '$104.78');
insert into books (id, author_id, title, price_old, price) values (120, 392, 'Adventure in Space and Time, An', '$63.67', '$120.98');
insert into books (id, author_id, title, price_old, price) values (121, 289, 'Storm in Summer, A', '$4.58', '$125.44');
insert into books (id, author_id, title, price_old, price) values (122, 364, 'Life According to Sam', '$10.52', '$188.07');
insert into books (id, author_id, title, price_old, price) values (123, 128, 'Rough Magic', '$116.51', '$66.29');
insert into books (id, author_id, title, price_old, price) values (124, 480, 'Love with the Proper Stranger', '$153.01', '$42.09');
insert into books (id, author_id, title, price_old, price) values (125, 321, 'Festival in Cannes', '$51.03', '$61.02');
insert into books (id, author_id, title, price_old, price) values (126, 117, 'Spriggan ', '$216.19', '$123.82');
insert into books (id, author_id, title, price_old, price) values (127, 227, 'Trapped in the Closet: Chapters 23-33', '$184.92', '$206.02');
insert into books (id, author_id, title, price_old, price) values (128, 144, 'Wild Oranges', '$220.15', '$14.92');
insert into books (id, author_id, title, price_old, price) values (129, 80, 'Back Stage', '$93.26', '$52.36');
insert into books (id, author_id, title, price_old, price) values (130, 211, 'Farscape: The Peacekeeper Wars', '$233.66', '$220.63');
insert into books (id, author_id, title, price_old, price) values (131, 220, 'Stolen Summer', '$119.99', '$164.36');
insert into books (id, author_id, title, price_old, price) values (132, 136, 'Reggie Watts: Why Shit So Crazy?', '$104.78', '$125.92');
insert into books (id, author_id, title, price_old, price) values (133, 129, 'Howards of Virginia, The', '$114.91', '$90.16');
insert into books (id, author_id, title, price_old, price) values (134, 214, 'Woman in the Moon', '$8.17', '$211.55');
insert into books (id, author_id, title, price_old, price) values (135, 495, 'Rocket', '$225.88', '$117.10');
insert into books (id, author_id, title, price_old, price) values (136, 393, 'Casanova', '$102.29', '$215.06');
insert into books (id, author_id, title, price_old, price) values (137, 479, 'Ashes, The (Popioly)', '$154.31', '$100.68');
insert into books (id, author_id, title, price_old, price) values (138, 197, 'Kukuli', '$13.43', '$244.48');
insert into books (id, author_id, title, price_old, price) values (139, 131, 'Anything But Love (a.k.a. Standard Time)', '$193.23', '$18.38');
insert into books (id, author_id, title, price_old, price) values (140, 242, 'If You Could Only Cook', '$1.54', '$55.15');
insert into books (id, author_id, title, price_old, price) values (141, 374, 'Mon Oncle Antoine', '$9.05', '$12.10');
insert into books (id, author_id, title, price_old, price) values (142, 26, 'The Heavy', '$129.73', '$109.93');
insert into books (id, author_id, title, price_old, price) values (143, 447, 'Two Ninas', '$167.73', '$34.65');
insert into books (id, author_id, title, price_old, price) values (144, 292, 'Night and Fog', '$240.14', '$134.17');
insert into books (id, author_id, title, price_old, price) values (145, 6, 'Last of the Unjust', '$200.53', '$120.48');
insert into books (id, author_id, title, price_old, price) values (146, 467, 'Monsieur Vincent', '$92.88', '$228.42');
insert into books (id, author_id, title, price_old, price) values (147, 285, 'T-Rex: Back to the Cretaceous', '$152.09', '$62.10');
insert into books (id, author_id, title, price_old, price) values (148, 398, 'Gone Fishin', '$18.08', '$122.31');
insert into books (id, author_id, title, price_old, price) values (149, 280, 'My Foolish Heart', '$10.86', '$58.33');
insert into books (id, author_id, title, price_old, price) values (150, 57, 'Tyler Perrys Temptation: Confessions of a Marriage Counselor', '$59.39', '$43.55');
insert into books (id, author_id, title, price_old, price) values (151, 184, 'Katie Tippel', '$40.51', '$33.30');
insert into books (id, author_id, title, price_old, price) values (152, 169, 'Milk of Sorrow, The', '$187.81', '$170.39');
insert into books (id, author_id, title, price_old, price) values (153, 43, 'Through a Glass Darkly', '$133.36', '$49.39');
insert into books (id, author_id, title, price_old, price) values (154, 215, 'Many Adventures of Winnie the Pooh, The', '$224.85', '$152.67');
insert into books (id, author_id, title, price_old, price) values (155, 50, 'Animal Room', '$19.44', '$156.31');
insert into books (id, author_id, title, price_old, price) values (156, 147, 'Life or Something Like It', '$186.94', '$160.57');
insert into books (id, author_id, title, price_old, price) values (157, 339, 'Leila', '$167.90', '$22.48');
insert into books (id, author_id, title, price_old, price) values (158, 477, 'This Is the Night', '$0.45', '$66.35');
insert into books (id, author_id, title, price_old, price) values (159, 184, 'Horror Planet', '$152.86', '$232.84');
insert into books (id, author_id, title, price_old, price) values (160, 290, 'Young Lions, The', '$198.33', '$148.54');
insert into books (id, author_id, title, price_old, price) values (161, 99, 'Stations of the Cross', '$74.43', '$160.49');
insert into books (id, author_id, title, price_old, price) values (162, 118, 'Accident on Hill Road', '$31.38', '$113.08');
insert into books (id, author_id, title, price_old, price) values (163, 200, 'Just Write', '$3.53', '$144.83');
insert into books (id, author_id, title, price_old, price) values (164, 211, 'Purple Rain', '$245.17', '$190.11');
insert into books (id, author_id, title, price_old, price) values (165, 389, 'Blazing Saddles', '$153.63', '$215.71');
insert into books (id, author_id, title, price_old, price) values (166, 93, 'Straight Story, The', '$233.07', '$86.47');
insert into books (id, author_id, title, price_old, price) values (167, 290, 'Sexual Chronicles of a French Family', '$7.63', '$83.72');
insert into books (id, author_id, title, price_old, price) values (168, 38, 'Vince Vaughn''s Wild West Comedy Show: 30 Days & 30 Nights - Hollywood to the Heartland', '$168.18', '$106.61');
insert into books (id, author_id, title, price_old, price) values (169, 416, 'Long Voyage Home, The', '$57.20', '$125.98');
insert into books (id, author_id, title, price_old, price) values (170, 56, 'Chicago 10', '$162.16', '$45.33');
insert into books (id, author_id, title, price_old, price) values (171, 234, 'Running on Empty', '$140.46', '$214.92');
insert into books (id, author_id, title, price_old, price) values (172, 495, 'Maid of Salem', '$147.71', '$78.15');
insert into books (id, author_id, title, price_old, price) values (173, 26, 'Downfall', '$211.31', '$40.11');
insert into books (id, author_id, title, price_old, price) values (174, 374, 'Flight of the Living Dead', '$135.49', '$217.22');
insert into books (id, author_id, title, price_old, price) values (175, 358, 'Paradise for Three', '$193.64', '$189.28');
insert into books (id, author_id, title, price_old, price) values (176, 244, 'American Dreams in China', '$209.43', '$238.46');
insert into books (id, author_id, title, price_old, price) values (177, 282, 'Bit by Bit', '$215.15', '$223.25');
insert into books (id, author_id, title, price_old, price) values (178, 190, 'Winds of the Wasteland', '$241.32', '$27.81');
insert into books (id, author_id, title, price_old, price) values (179, 334, 'Black Cauldron, The', '$93.29', '$168.73');
insert into books (id, author_id, title, price_old, price) values (180, 163, 'Hitler: A Film from Germany', '$216.02', '$92.58');
insert into books (id, author_id, title, price_old, price) values (181, 82, 'Old San Francisco', '$12.61', '$225.81');
insert into books (id, author_id, title, price_old, price) values (182, 55, 'For Love of the Game', '$192.75', '$33.04');
insert into books (id, author_id, title, price_old, price) values (183, 146, 'Flowers of St. Francis ', '$222.80', '$19.45');
insert into books (id, author_id, title, price_old, price) values (184, 107, 'Tartuffe', '$200.70', '$247.71');
insert into books (id, author_id, title, price_old, price) values (185, 351, 'Young Man with a Horn', '$202.79', '$142.34');
insert into books (id, author_id, title, price_old, price) values (186, 373, 'Holy Wars', '$168.43', '$229.29');
insert into books (id, author_id, title, price_old, price) values (187, 369, 'Hellboy', '$75.65', '$219.81');
insert into books (id, author_id, title, price_old, price) values (188, 54, 'Midnight Man', '$97.30', '$121.62');
insert into books (id, author_id, title, price_old, price) values (189, 415, 'The Face of Marble', '$176.65', '$127.70');
insert into books (id, author_id, title, price_old, price) values (190, 494, 'Herbie: Fully Loaded', '$249.32', '$207.56');
insert into books (id, author_id, title, price_old, price) values (191, 490, 'Trainspotting', '$223.36', '$1.23');
insert into books (id, author_id, title, price_old, price) values (192, 269, 'Tarzan''s Magic Fountain', '$73.61', '$156.96');
insert into books (id, author_id, title, price_old, price) values (193, 75, 'RoboCop 3', '$75.17', '$151.78');
insert into books (id, author_id, title, price_old, price) values (194, 156, 'Shrooms', '$239.18', '$57.69');
insert into books (id, author_id, title, price_old, price) values (195, 109, 'Roots', '$231.15', '$29.06');
insert into books (id, author_id, title, price_old, price) values (196, 34, 'Keep, The', '$214.39', '$90.54');
insert into books (id, author_id, title, price_old, price) values (197, 125, 'Dominion Tank Police', '$174.65', '$125.53');
insert into books (id, author_id, title, price_old, price) values (198, 121, 'Drugstore Cowboy', '$90.24', '$83.82');
insert into books (id, author_id, title, price_old, price) values (199, 309, 'Cop Out', '$64.08', '$212.93');
insert into books (id, author_id, title, price_old, price) values (200, 348, 'Hood of the Living Dead', '$220.71', '$220.40');
insert into books (id, author_id, title, price_old, price) values (201, 42, 'Happy Together', '$83.76', '$117.29');
insert into books (id, author_id, title, price_old, price) values (202, 320, 'Four-Faced Liar, The', '$222.10', '$15.53');
insert into books (id, author_id, title, price_old, price) values (203, 449, 'The Message', '$99.92', '$212.66');
insert into books (id, author_id, title, price_old, price) values (204, 29, 'Just My Luck', '$87.19', '$217.68');
insert into books (id, author_id, title, price_old, price) values (205, 400, 'Riding in Cars with Boys', '$32.33', '$150.06');
insert into books (id, author_id, title, price_old, price) values (206, 59, 'Tyson', '$67.85', '$220.43');
insert into books (id, author_id, title, price_old, price) values (207, 151, 'I, Frankenstein', '$199.98', '$15.66');
insert into books (id, author_id, title, price_old, price) values (208, 467, 'Sugar Curtain', '$174.09', '$177.18');
insert into books (id, author_id, title, price_old, price) values (209, 451, 'Man Who Planted Trees', '$81.08', '$114.56');
insert into books (id, author_id, title, price_old, price) values (210, 156, 'Supermensch: The Legend of Shep Gordon', '$141.51', '$234.30');
insert into books (id, author_id, title, price_old, price) values (211, 211, 'King of Comedy, The', '$62.05', '$12.37');
insert into books (id, author_id, title, price_old, price) values (212, 15, 'Beneath the Rooftops of Paris', '$102.17', '$134.41');
insert into books (id, author_id, title, price_old, price) values (213, 184, 'Secrets of the Tribe', '$182.11', '$131.97');
insert into books (id, author_id, title, price_old, price) values (214, 448, 'Idol of the Crowds', '$52.66', '$102.28');
insert into books (id, author_id, title, price_old, price) values (215, 153, 'Off the Black', '$182.27', '$164.73');
insert into books (id, author_id, title, price_old, price) values (216, 374, 'Oil, the Baby and the Transylvanians', '$207.76', '$182.41');
insert into books (id, author_id, title, price_old, price) values (217, 279, 'Hellbenders', '$171.32', '$98.89');
insert into books (id, author_id, title, price_old, price) values (218, 98, 'Frank', '$108.36', '$95.68');
insert into books (id, author_id, title, price_old, price) values (219, 207, 'The Great Scout & Cathouse Thursday', '$200.67', '$231.68');
insert into books (id, author_id, title, price_old, price) values (220, 387, 'Zebrahead', '$92.13', '$70.47');
insert into books (id, author_id, title, price_old, price) values (221, 129, 'Reservation Road', '$121.44', '$64.26');
insert into books (id, author_id, title, price_old, price) values (222, 430, 'The Town that Dreaded Sundown', '$153.65', '$242.88');
insert into books (id, author_id, title, price_old, price) values (223, 432, 'The Woman on Pier 13', '$142.38', '$209.80');
insert into books (id, author_id, title, price_old, price) values (224, 278, 'Chicago Joe and the Showgirl', '$78.17', '$164.43');
insert into books (id, author_id, title, price_old, price) values (225, 89, 'Sheena', '$145.07', '$117.84');
insert into books (id, author_id, title, price_old, price) values (226, 427, 'Gunfight at the O.K. Corral', '$153.66', '$231.40');
insert into books (id, author_id, title, price_old, price) values (227, 227, 'Wheel of Time', '$107.43', '$176.72');
insert into books (id, author_id, title, price_old, price) values (228, 462, 'Parenti serpenti', '$242.08', '$174.99');
insert into books (id, author_id, title, price_old, price) values (229, 223, 'Sense and Sensibility', '$44.14', '$113.29');
insert into books (id, author_id, title, price_old, price) values (230, 129, 'Alpha and Omega 3: The Great Wolf Games', '$10.09', '$33.64');
insert into books (id, author_id, title, price_old, price) values (231, 339, 'Jönssonligan på Mallorca', '$165.30', '$25.46');
insert into books (id, author_id, title, price_old, price) values (232, 237, 'Down to the Sea in Ships', '$139.64', '$116.40');
insert into books (id, author_id, title, price_old, price) values (233, 189, 'Border Run (Mule, The)', '$117.58', '$218.95');
insert into books (id, author_id, title, price_old, price) values (234, 496, 'Pink Panther Strikes Again, The', '$221.39', '$198.00');
insert into books (id, author_id, title, price_old, price) values (235, 248, 'Pelle Svanslös i Amerikatt', '$207.50', '$23.75');
insert into books (id, author_id, title, price_old, price) values (236, 451, 'Desert Hearts', '$74.60', '$240.84');
insert into books (id, author_id, title, price_old, price) values (237, 302, 'Jeremy', '$230.67', '$38.26');
insert into books (id, author_id, title, price_old, price) values (238, 57, 'Drunks', '$139.56', '$9.81');
insert into books (id, author_id, title, price_old, price) values (239, 362, 'Exam', '$191.07', '$238.72');
insert into books (id, author_id, title, price_old, price) values (240, 334, 'Singin in the Rain', '$248.39', '$199.58');
insert into books (id, author_id, title, price_old, price) values (241, 243, 'Telstar: The Joe Meek Story', '$139.97', '$20.91');
insert into books (id, author_id, title, price_old, price) values (242, 242, 'Officer and a Gentleman, An', '$138.76', '$32.08');
insert into books (id, author_id, title, price_old, price) values (243, 387, 'The Good Son', '$233.49', '$206.66');
insert into books (id, author_id, title, price_old, price) values (244, 84, 'Personal Journey with Martin Scorsese Through American Movies, A', '$98.74', '$14.42');
insert into books (id, author_id, title, price_old, price) values (245, 366, 'Dick Figures: The Movie', '$63.55', '$30.54');
insert into books (id, author_id, title, price_old, price) values (246, 42, 'Life Is Beautiful', '$36.15', '$227.62');
insert into books (id, author_id, title, price_old, price) values (247, 230, 'Delta of Venus', '$106.49', '$144.19');
insert into books (id, author_id, title, price_old, price) values (248, 431, 'Goldfish Memory', '$186.04', '$121.06');
insert into books (id, author_id, title, price_old, price) values (249, 428, 'Vlad Tepes', '$193.44', '$70.96');
insert into books (id, author_id, title, price_old, price) values (250, 402, 'We Own the Night', '$206.05', '$148.72');